/* automatically generated from xfwm4-tweaks-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tweaks_dialog_ui)
#endif
#ifdef __GNUC__
static const char tweaks_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char tweaks_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><object class=\"Gt"
  "kAdjustment\" id=\"adjustment1\"><property name=\"upper\">100</property"
  "><property name=\"value\">75</property><property name=\"step_increment\""
  ">1</property><property name=\"page_increment\">10</property></object><o"
  "bject class=\"GtkAdjustment\" id=\"adjustment2\"><property name=\"upper"
  "\">100</property><property name=\"value\">90</property><property name=\""
  "step_increment\">1</property><property name=\"page_increment\">10</prop"
  "erty></object><object class=\"GtkAdjustment\" id=\"adjustment3\"><prope"
  "rty name=\"upper\">100</property><property name=\"value\">90</property>"
  "<property name=\"step_increment\">1</property><property name=\"page_inc"
  "rement\">10</property></object><object class=\"GtkAdjustment\" id=\"adj"
  "ustment4\"><property name=\"upper\">100</property><property name=\"valu"
  "e\">90</property><property name=\"step_increment\">1</property><propert"
  "y name=\"page_increment\">10</property></object><object class=\"GtkAdju"
  "stment\" id=\"adjustment5\"><property name=\"upper\">100</property><pro"
  "perty name=\"value\">90</property><property name=\"step_increment\">1</"
  "property><property name=\"page_increment\">10</property></object><objec"
  "t class=\"GtkAdjustment\" id=\"adjustment6\"><property name=\"upper\">1"
  "00</property><property name=\"value\">90</property><property name=\"ste"
  "p_increment\">1</property><property name=\"page_increment\">10</propert"
  "y></object><object class=\"XfceTitledDialog\" id=\"main-dialog\"><prope"
  "rty name=\"can_focus\">False</property><property name=\"title\" transla"
  "table=\"yes\">Window Manager Tweaks</property><property name=\"window_p"
  "osition\">center-on-parent</property><property name=\"default_height\">"
  "480</property><property name=\"icon_name\">wmtweaks</property><property"
  " name=\"type_hint\">dialog</property><property name=\"subtitle\" transl"
  "atable=\"yes\">Fine-tune window behaviour and effects</property><child "
  "internal-child=\"vbox\"><object class=\"GtkBox\" id=\"main-vbox\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"orientation\">vertical</property><child int"
  "ernal-child=\"action_area\"><object class=\"GtkButtonBox\" id=\"dialog-"
  "action_area1\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"orientation\">horizonta"
  "l</property><property name=\"layout_style\">end</property><child><objec"
  "t class=\"GtkButton\" id=\"button2\"><property name=\"label\">gtk-help<"
  "/property><property name=\"use_action_appearance\">False</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">True"
  "</property><property name=\"receives_default\">True</property><property"
  " name=\"use_stock\">True</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">0</property><property name=\"secondary\">True</pro"
  "perty></packing></child><child><object class=\"GtkButton\" id=\"button1"
  "\"><property name=\"label\">gtk-close</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">True</property><property name=\"use_stock\">True</propert"
  "y></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">1</property>"
  "</packing></child></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"pack_typ"
  "e\">end</property><property name=\"position\">0</property></packing></c"
  "hild><child><object class=\"GtkNotebook\" id=\"plug-child\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True</prope"
  "rty><property name=\"border_width\">6</property><child><object class=\""
  "GtkBox\" id=\"vbox1\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"orientation\">ve"
  "rtical</property><property name=\"border_width\">12</property><property"
  " name=\"spacing\">6</property><child><object class=\"GtkCheckButton\" i"
  "d=\"cycle_minimum_check\"><property name=\"label\" translatable=\"yes\""
  ">S_kip windows that have \"skip pager\"\nor \"skip taskbar\" properties"
  " set</property><property name=\"use_action_appearance\">False</property"
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">False</property><pr"
  "operty name=\"use_underline\">True</property><property name=\"draw_indi"
  "cator\">True</property></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">0</property></packing></child><child><object class=\"GtkCheckB"
  "utton\" id=\"cycle_hidden_check\"><property name=\"label\" translatable"
  "=\"yes\">_Include hidden (i.e. iconified) windows</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">1</property></pack"
  "ing></child><child><object class=\"GtkCheckButton\" id=\"cycle_workspac"
  "es_check\"><property name=\"label\" translatable=\"yes\">Cycle _through"
  " windows on all workspaces</property><property name=\"use_action_appear"
  "ance\">False</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"draw_indicator\">True</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">2</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"cycle_draw_frame\"><property name=\""
  "label\" translatable=\"yes\">_Draw frame around selected windows while "
  "cycling</property><property name=\"use_action_appearance\">False</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">False</property>"
  "<property name=\"use_underline\">True</property><property name=\"draw_i"
  "ndicator\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">3</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"cycle_raise\"><property name=\"label\" translatable=\"ye"
  "s\">_Raise windows while cycling</property><property name=\"use_action_"
  "appearance\">False</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">False</property><property name=\"use_underline\">True</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">4</property></packing></child><chi"
  "ld><object class=\"GtkCheckButton\" id=\"cycle_tabwin_mode\"><property "
  "name=\"label\" translatable=\"yes\">Cycle through windows in a _list</p"
  "roperty><property name=\"use_action_appearance\">False</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">5</property></packing></child></object></child><child type=\"tab\"><ob"
  "ject class=\"GtkLabel\" id=\"label1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">C_ycling</property><property name=\"use_un"
  "derline\">True</property></object><packing><property name=\"tab_fill\">"
  "False</property></packing></child><child><object class=\"GtkBox\" id=\""
  "vbox3\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"orientation\">vertical</proper"
  "ty><property name=\"border_width\">12</property><property name=\"spacin"
  "g\">6</property><child><object class=\"GtkCheckButton\" id=\"prevent_fo"
  "cus_stealing_check\"><property name=\"label\" translatable=\"yes\">Acti"
  "vate foc_us stealing prevention</property><property name=\"use_action_a"
  "ppearance\">False</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"receives_de"
  "fault\">False</property><property name=\"use_underline\">True</property"
  "><property name=\"draw_indicator\">True</property></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">False</p"
  "roperty><property name=\"position\">0</property></packing></child><chil"
  "d><object class=\"GtkCheckButton\" id=\"focus_hint_check\"><property na"
  "me=\"label\" translatable=\"yes\">Honor _standard ICCCM focus hint</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "1</property></packing></child><child><object class=\"GtkBox\" id=\"prev"
  "ent_focus_stealing_box\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"orientation\""
  ">vertical</property><property name=\"spacing\">6</property><child><obje"
  "ct class=\"GtkLabel\" id=\"label11\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"x"
  "align\">0</property><property name=\"label\" translatable=\"yes\">When "
  "a window raises itself:</property></object><packing><property name=\"ex"
  "pand\">True</property><property name=\"fill\">True</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkAlignment\" id=\"alignment2\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"botto"
  "m_padding\">6</property><property name=\"left_padding\">12</property><c"
  "hild><object class=\"GtkBox\" id=\"vbox14\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"orientation\">vertical</property><property name=\"border_width\">"
  "6</property><property name=\"spacing\">6</property><child><object class"
  "=\"GtkRadioButton\" id=\"activate_action_bring_option\"><property name="
  "\"label\" translatable=\"yes\">_Bring window on current workspace</prop"
  "erty><property name=\"use_action_appearance\">False</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"use_underline\">True</property><property name=\"active\">True</prop"
  "erty><property name=\"draw_indicator\">True</property></object><packing"
  "><property name=\"expand\">True</property><property name=\"fill\">True<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkRadioButton\" id=\"activate_action_switch_option"
  "\"><property name=\"label\" translatable=\"yes\">Switch to win_dow\'s w"
  "orkspace</property><property name=\"use_action_appearance\">False</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">False</property"
  "><property name=\"use_underline\">True</property><property name=\"activ"
  "e\">True</property><property name=\"draw_indicator\">True</property><pr"
  "operty name=\"group\">activate_action_bring_option</property></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld><child><object class=\"GtkRadioButton\" id=\"activate_action_none_op"
  "tion\"><property name=\"label\" translatable=\"yes\">Do _nothing</prope"
  "rty><property name=\"use_action_appearance\">False</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">False</property><property name"
  "=\"use_underline\">True</property><property name=\"active\">True</prope"
  "rty><property name=\"draw_indicator\">True</property><property name=\"g"
  "roup\">activate_action_bring_option</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">2</property></packing></child></object></"
  "child></object><packing><property name=\"expand\">True</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">1</propert"
  "y></packing></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">2</property></packing></child></object><packing><property name=\""
  "position\">1</property></packing></child><child type=\"tab\"><object cl"
  "ass=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">_Focus</property><property name=\"use_underline\""
  ">True</property></object><packing><property name=\"position\">1</proper"
  "ty><property name=\"tab_fill\">False</property></packing></child><child"
  "><object class=\"GtkBox\" id=\"vbox4\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "orientation\">vertical</property><property name=\"border_width\">12</pr"
  "operty><property name=\"spacing\">6</property><child><object class=\"Gt"
  "kBox\" id=\"hbox1\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"orientation\">hori"
  "zontal</property><property name=\"spacing\">12</property><child><object"
  " class=\"GtkLabel\" id=\"label7\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"xali"
  "gn\">0</property><property name=\"label\" translatable=\"yes\">Key used"
  " to _grab and move windows:</property><property name=\"use_underline\">"
  "True</property><property name=\"mnemonic_widget\">easy_click_combo_box<"
  "/property></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkComboBox\" id=\"eas"
  "y_click_combo_box\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">1</property></packing></child></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">False<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkCheckButton\" id=\"raise_with_any_button_check\""
  "><property name=\"label\" translatable=\"yes\">_Raise windows when any "
  "mouse button is pressed</property><property name=\"use_action_appearanc"
  "e\">False</property><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"receives_default\">"
  "False</property><property name=\"use_underline\">True</property><proper"
  "ty name=\"draw_indicator\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">1</property></packing></child><child><objec"
  "t class=\"GtkCheckButton\" id=\"borderless_maximize_check\"><property n"
  "ame=\"label\" translatable=\"yes\">Hide frame of windows when ma_ximize"
  "d</property><property name=\"use_action_appearance\">False</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">False</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"draw_indicat"
  "or\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">2</property></packing></child><child><object class=\"GtkCheckButt"
  "on\" id=\"titleless_maximize_check\"><property name=\"label\" translata"
  "ble=\"yes\">Hide title of windows when maximized</property><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">3</pr"
  "operty></packing></child><child><object class=\"GtkCheckButton\" id=\"t"
  "ile_on_move_check\"><property name=\"label\" translatable=\"yes\">Autom"
  "atically _tile windows when moving toward the screen edge</property><pr"
  "operty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">4</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"snap_"
  "resist_check\"><property name=\"label\" translatable=\"yes\">Use _edge "
  "resistance instead of window snapping</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"draw_indicator\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">5</property></packing></child"
  "><child><object class=\"GtkCheckButton\" id=\"urgent_blink\"><property "
  "name=\"label\" translatable=\"yes\">Notify of _urgency by making window"
  "\'s decoration blink</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">6</property></packing></child><child><object c"
  "lass=\"GtkCheckButton\" id=\"repeat_urgent_blink\"><property name=\"lab"
  "el\" translatable=\"yes\">Keep urgent windows _blinking repeatedly</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "7</property></packing></child><child><object class=\"GtkCheckButton\" i"
  "d=\"mousewheel_rollup\"><property name=\"label\" translatable=\"yes\">U"
  "se mouse wheel on title bar to ro_ll up the window</property><property "
  "name=\"use_action_appearance\">False</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">False</property><property name=\"use_underli"
  "ne\">True</property><property name=\"draw_indicator\">True</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">7</property></pa"
  "cking></child></object><packing><property name=\"position\">2</property"
  "></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label3\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "_Accessibility</property><property name=\"use_underline\">True</propert"
  "y></object><packing><property name=\"position\">2</property><property n"
  "ame=\"tab_fill\">False</property></packing></child><child><object class"
  "=\"GtkBox\" id=\"vbox5\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"orientation\""
  ">vertical</property><property name=\"border_width\">12</property><prope"
  "rty name=\"spacing\">6</property><child><object class=\"GtkCheckButton\""
  " id=\"scroll_workspaces_check\"><property name=\"label\" translatable=\""
  "yes\">Use the _mouse wheel on the desktop to switch workspaces</propert"
  "y><property name=\"use_action_appearance\">False</property><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">True</proper"
  "ty><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkCheckButton\" id=\"t"
  "oggle_workspaces_check\"><property name=\"label\" translatable=\"yes\">"
  "_Remember and recall previous workspace\nwhen switching via keyboard sh"
  "ortcuts</property><property name=\"use_action_appearance\">False</prope"
  "rty><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><property name=\"receives_default\">False</property>"
  "<property name=\"use_underline\">True</property><property name=\"draw_i"
  "ndicator\">True</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">False</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkChec"
  "kButton\" id=\"wrap_layout_check\"><property name=\"label\" translatabl"
  "e=\"yes\">Wrap workspaces depending on the actual desktop _layout</prop"
  "erty><property name=\"use_action_appearance\">False</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"use_underline\">True</property><property name=\"draw_indicator\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">2"
  "</property></packing></child><child><object class=\"GtkCheckButton\" id"
  "=\"wrap_cycle_check\"><property name=\"label\" translatable=\"yes\">Wra"
  "p workspaces when _the first or the last workspace is reached</property"
  "><property name=\"use_action_appearance\">False</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">3</pr"
  "operty></packing></child></object><packing><property name=\"position\">"
  "3</property></packing></child><child type=\"tab\"><object class=\"GtkLa"
  "bel\" id=\"label4\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"label\" translatab"
  "le=\"yes\">_Workspaces</property><property name=\"use_underline\">True<"
  "/property></object><packing><property name=\"position\">3</property><pr"
  "operty name=\"tab_fill\">False</property></packing></child><child><obje"
  "ct class=\"GtkBox\" id=\"vbox6\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"orien"
  "tation\">vertical</property><property name=\"border_width\">12</propert"
  "y><property name=\"spacing\">6</property><child><object class=\"GtkLabe"
  "l\" id=\"label8\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"xalign\">0</property"
  "><property name=\"label\" translatable=\"yes\">_Minimum size of windows"
  " to trigger smart placement:</property><property name=\"use_underline\""
  ">True</property><property name=\"mnemonic_widget\">placement_ratio_scal"
  "e</property></object><packing><property name=\"expand\">False</property"
  "><property name=\"fill\">False</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkAlignment\" id=\""
  "alignment4\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"bottom_padding\">6</proper"
  "ty><property name=\"left_padding\">12</property><child><object class=\""
  "GtkBox\" id=\"hbox2\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"orientation\">ho"
  "rizontal</property><property name=\"spacing\">12</property><child><obje"
  "ct class=\"GtkLabel\" id=\"label9\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\" comments=\"Smart placement size\">&lt;i&gt;S"
  "mall&lt;/i&gt;</property><property name=\"use_markup\">True</property><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkScale\" id=\"placement_ratio_s"
  "cale\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"orientation\">horizontal</proper"
  "ty><property name=\"adjustment\">adjustment1</property><property name=\""
  "restrict_to_fill_level\">False</property><property name=\"draw_value\">"
  "False</property></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "1</property></packing></child><child><object class=\"GtkLabel\" id=\"la"
  "bel10\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label\" translatable=\"yes\" c"
  "omments=\"Smart placement size\">&lt;i&gt;Large&lt;/i&gt;</property><pr"
  "operty name=\"use_markup\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">2</property></packing></child></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">1</property"
  "></packing></child><child><object class=\"GtkBox\" id=\"default_placeme"
  "nt_box\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"orientation\">vertical</prope"
  "rty><property name=\"spacing\">6</property><child><object class=\"GtkLa"
  "bel\" id=\"label27\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"xalign\">0</prope"
  "rty><property name=\"label\" translatable=\"yes\">By default, place win"
  "dows:</property></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkAlignment\" id="
  "\"alignment10\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"bottom_padding\">6</pr"
  "operty><property name=\"left_padding\">12</property><child><object clas"
  "s=\"GtkBox\" id=\"vbox18\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"orientation"
  "\">vertical</property><property name=\"border_width\">6</property><prop"
  "erty name=\"spacing\">6</property><child><object class=\"GtkRadioButton"
  "\" id=\"placement_center_option\"><property name=\"label\" translatable"
  "=\"yes\">At the c_enter of the screen</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"draw_indicator\">True</property></object><packi"
  "ng><property name=\"expand\">True</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkRadioButton\" id=\"placement_mouse_option\"><p"
  "roperty name=\"label\" translatable=\"yes\">U_nder the mouse pointer</p"
  "roperty><property name=\"use_action_appearance\">False</property><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">True</"
  "property><property name=\"receives_default\">False</property><property "
  "name=\"use_underline\">True</property><property name=\"active\">True</p"
  "roperty><property name=\"draw_indicator\">True</property><property name"
  "=\"group\">placement_center_option</property></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">1</property></packing></child></object></c"
  "hild></object><packing><property name=\"expand\">True</property><proper"
  "ty name=\"fill\">True</property><property name=\"position\">1</property"
  "></packing></child></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">False</property><property name=\"positi"
  "on\">2</property></packing></child></object><packing><property name=\"p"
  "osition\">4</property></packing></child><child type=\"tab\"><object cla"
  "ss=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">False</property><property name=\"label\" "
  "translatable=\"yes\">_Placement</property><property name=\"use_underlin"
  "e\">True</property></object><packing><property name=\"position\">4</pro"
  "perty><property name=\"tab_fill\">False</property></packing></child><ch"
  "ild><object class=\"GtkBox\" id=\"vbox7\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"orientation\">vertical</property><property name=\"border_width\">12"
  "</property><property name=\"spacing\">6</property><child><object class="
  "\"GtkCheckButton\" id=\"use_compositing_check\"><property name=\"label\""
  " translatable=\"yes\">_Enable display compositing</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">0</property></pack"
  "ing></child><child><object class=\"GtkScrolledWindow\" id=\"use_composi"
  "ting_box\"><property name=\"visible\">True</property><property name=\"s"
  "ensitive\">False</property><property name=\"can_focus\">True</property>"
  "<property name=\"hscrollbar_policy\">never</property><property name=\"v"
  "scrollbar_policy\">automatic</property><child><object class=\"GtkViewpo"
  "rt\" id=\"viewport1\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"resize_mode\">qu"
  "eue</property><property name=\"shadow_type\">none</property><child><obj"
  "ect class=\"GtkAlignment\" id=\"alignment3\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"bottom_padding\">6</property><property name=\"left_padding\">12<"
  "/property><child><object class=\"GtkBox\" id=\"vbox8\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"orientation\">vertical</property><property name=\"spaci"
  "ng\">6</property><child><object class=\"GtkCheckButton\" id=\"unredirec"
  "t_overlays_check\"><property name=\"label\" translatable=\"yes\">Displa"
  "y _fullscreen overlay windows directly</property><property name=\"use_a"
  "ction_appearance\">False</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"rece"
  "ives_default\">False</property><property name=\"use_underline\">True</p"
  "roperty><property name=\"draw_indicator\">True</property></object><pack"
  "ing><property name=\"expand\">False</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkCheckButton\" id=\"cycle_preview_check\"><pr"
  "operty name=\"label\" translatable=\"yes\">Show windows preview in plac"
  "e of icons when cycling</property><property name=\"use_action_appearanc"
  "e\">False</property><property name=\"visible\">True</property><property"
  " name=\"can_focus\">True</property><property name=\"receives_default\">"
  "False</property><property name=\"use_underline\">True</property><proper"
  "ty name=\"draw_indicator\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">2</property></packing></child><child><object"
  " class=\"GtkCheckButton\" id=\"show_popup_shadow_check\"><property name"
  "=\"label\" translatable=\"yes\">Show shadows under pop_up windows</prop"
  "erty><property name=\"use_action_appearance\">False</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"use_underline\">True</property><property name=\"draw_indicator\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">3<"
  "/property></packing></child><child><object class=\"GtkCheckButton\" id="
  "\"show_dock_shadow_check\"><property name=\"label\" translatable=\"yes\""
  ">Show shadows under _dock windows</property><property name=\"use_action"
  "_appearance\">False</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">False</property><property name=\"use_underline\">True</proper"
  "ty><property name=\"draw_indicator\">True</property></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">True</"
  "property><property name=\"position\">4</property></packing></child><chi"
  "ld><object class=\"GtkCheckButton\" id=\"show_frame_shadow_check\"><pro"
  "perty name=\"label\" translatable=\"yes\">Show shadows under _regular w"
  "indows</property><property name=\"use_action_appearance\">False</proper"
  "ty><property name=\"visible\">True</property><property name=\"can_focus"
  "\">True</property><property name=\"receives_default\">False</property><"
  "property name=\"use_underline\">True</property><property name=\"draw_in"
  "dicator\">True</property></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">5</property></packing></child><child><object class=\"GtkLabel"
  "\" id=\"label12\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"xalign\">0</property"
  "><property name=\"label\" translatable=\"yes\">Opaci_ty of window decor"
  "ations:</property><property name=\"use_underline\">True</property><prop"
  "erty name=\"mnemonic_widget\">frame_opacity_scale</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">6</property></packing></chi"
  "ld><child><object class=\"GtkAlignment\" id=\"alignment5\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"top_padding\">2</property><property name=\"left_pa"
  "dding\">12</property><child><object class=\"GtkBox\" id=\"hbox3\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"orientation\">horizontal</property><child><"
  "object class=\"GtkLabel\" id=\"label17\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"label\" translatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</propert"
  "y><property name=\"use_markup\">True</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">False</prop"
  "erty><property name=\"position\">0</property></packing></child><child><"
  "object class=\"GtkScale\" id=\"frame_opacity_scale\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"orientation\">horizontal</property><property name=\"adjus"
  "tment\">adjustment2</property><property name=\"restrict_to_fill_level\""
  ">False</property><property name=\"draw_value\">False</property></object"
  "><packing><property name=\"expand\">True</property><property name=\"fil"
  "l\">True</property><property name=\"position\">1</property></packing></"
  "child><child><object class=\"GtkLabel\" id=\"label18\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;<"
  "/property><property name=\"use_markup\">True</property></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"position\">2</property></packing></child>"
  "</object></child></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">False</property><property name=\"position"
  "\">7</property></packing></child><child><object class=\"GtkLabel\" id=\""
  "label13\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"xalign\">0</property><proper"
  "ty name=\"label\" translatable=\"yes\">Opacity of _inactive windows:</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"mnemonic_widget\">inactive_opacity_scale</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">8</property></packing></child><c"
  "hild><object class=\"GtkAlignment\" id=\"alignment6\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"top_padding\">2</property><property name=\"left_padding"
  "\">12</property><child><object class=\"GtkBox\" id=\"hbox4\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"orientation\">horizontal</property><child><objec"
  "t class=\"GtkLabel\" id=\"label19\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</property><pr"
  "operty name=\"use_markup\">True</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">False</property>"
  "<property name=\"position\">0</property></packing></child><child><objec"
  "t class=\"GtkScale\" id=\"inactive_opacity_scale\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">True</property><prop"
  "erty name=\"orientation\">horizontal</property><property name=\"adjustm"
  "ent\">adjustment3</property><property name=\"restrict_to_fill_level\">F"
  "alse</property><property name=\"draw_value\">False</property></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">1</property></packing></chi"
  "ld><child><object class=\"GtkLabel\" id=\"label20\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</p"
  "roperty><property name=\"use_markup\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">2</property></packing></child></"
  "object></child></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property><property name=\"position\""
  ">9</property></packing></child><child><object class=\"GtkLabel\" id=\"l"
  "abel14\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"xalign\">0</property><propert"
  "y name=\"label\" translatable=\"yes\">Opacity of windows during _move:<"
  "/property><property name=\"use_underline\">True</property><property nam"
  "e=\"mnemonic_widget\">move_opacity_scale</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">10</property></packing></child><ch"
  "ild><object class=\"GtkAlignment\" id=\"alignment7\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"top_padding\">2</property><property name=\"left_padding\""
  ">12</property><child><object class=\"GtkBox\" id=\"hbox5\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"orientation\">horizontal</property><child><object "
  "class=\"GtkLabel\" id=\"label21\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</property><prop"
  "erty name=\"use_markup\">True</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkScale\" id=\"move_opacity_scale\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"orientation\">horizontal</property><property name=\"adjustment\">"
  "adjustment4</property><property name=\"restrict_to_fill_level\">False</"
  "property><property name=\"draw_value\">False</property></object><packin"
  "g><property name=\"expand\">True</property><property name=\"fill\">True"
  "</property><property name=\"position\">1</property></packing></child><c"
  "hild><object class=\"GtkLabel\" id=\"label22\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</proper"
  "ty><property name=\"use_markup\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">2</property></packing></child></objec"
  "t></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">11</"
  "property></packing></child><child><object class=\"GtkLabel\" id=\"label"
  "15\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"xalign\">0</property><property na"
  "me=\"label\" translatable=\"yes\">Opacity of windows during resi_ze:</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"mnemonic_widget\">resize_opacity_scale</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">12</property></packing></child><ch"
  "ild><object class=\"GtkAlignment\" id=\"alignment8\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"top_padding\">2</property><property name=\"left_padding\""
  ">12</property><child><object class=\"GtkBox\" id=\"hbox6\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"orientation\">horizontal</property><child><object "
  "class=\"GtkLabel\" id=\"label23\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</property><prop"
  "erty name=\"use_markup\">True</property></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">False</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkScale\" id=\"resize_opacity_scale\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"orientation\">horizontal</property><property name=\"adjustment\""
  ">adjustment5</property><property name=\"restrict_to_fill_level\">False<"
  "/property><property name=\"draw_value\">False</property></object><packi"
  "ng><property name=\"expand\">True</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">1</property></packing></child><"
  "child><object class=\"GtkLabel\" id=\"label24\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</prope"
  "rty><property name=\"use_markup\">True</property></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">2</property></packing></child></obje"
  "ct></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">False</property><property name=\"position\">13<"
  "/property></packing></child><child><object class=\"GtkLabel\" id=\"labe"
  "l16\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"xalign\">0</property><property n"
  "ame=\"label\" translatable=\"yes\">Opacity of popup wi_ndows:</property"
  "><property name=\"use_underline\">True</property><property name=\"mnemo"
  "nic_widget\">popup_opacity_scale</property></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">14</property></packing></child><child><obj"
  "ect class=\"GtkAlignment\" id=\"alignment9\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"top_padding\">2</property><property name=\"left_padding\">12</pr"
  "operty><child><object class=\"GtkBox\" id=\"hbox7\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"orientation\">horizontal</property><child><object class=\""
  "GtkLabel\" id=\"label25\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</property><property nam"
  "e=\"use_markup\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkScale\" id=\"popup_opacity_scale\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"o"
  "rientation\">horizontal</property><property name=\"adjustment\">adjustm"
  "ent6</property><property name=\"restrict_to_fill_level\">False</propert"
  "y><property name=\"draw_value\">False</property></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child><child><o"
  "bject class=\"GtkLabel\" id=\"label26\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><pro"
  "perty name=\"use_markup\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">2</property></packing></child></object></chi"
  "ld></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">15</propert"
  "y></packing></child></object></child></object></child></object></child>"
  "</object><packing><property name=\"expand\">True</property><property na"
  "me=\"fill\">True</property><property name=\"position\">1</property></pa"
  "cking></child></object><packing><property name=\"position\">5</property"
  "></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label6\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "C_ompositor</property><property name=\"use_underline\">True</property><"
  "/object><packing><property name=\"position\">5</property><property name"
  "=\"tab_fill\">False</property></packing></child></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child></object>"
  "</child><action-widgets><action-widget response=\"-11\">button2</action"
  "-widget><action-widget response=\"0\">button1</action-widget></action-w"
  "idgets></object></interface>"
};

static const unsigned tweaks_dialog_ui_length = 46085u;

