/* automatically generated from xfwm4-workspace-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (workspace_dialog_ui)
#endif
#ifdef __GNUC__
static const char workspace_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char workspace_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkAdjustment\" id=\"adjustment1"
  "\"><property name=\"lower\">1</property><property name=\"upper\">100</p"
  "roperty><property name=\"step_increment\">1</property><property name=\""
  "page_increment\">10</property></object><object class=\"GtkAdjustment\" "
  "id=\"adjustment2\"><property name=\"upper\">100</property><property nam"
  "e=\"step_increment\">1</property><property name=\"page_increment\">10</"
  "property></object><object class=\"GtkAdjustment\" id=\"adjustment3\"><p"
  "roperty name=\"upper\">100</property><property name=\"step_increment\">"
  "1</property><property name=\"page_increment\">10</property></object><ob"
  "ject class=\"GtkAdjustment\" id=\"adjustment4\"><property name=\"upper\""
  ">100</property><property name=\"step_increment\">1</property><property "
  "name=\"page_increment\">10</property></object><object class=\"GtkAdjust"
  "ment\" id=\"adjustment5\"><property name=\"upper\">100</property><prope"
  "rty name=\"step_increment\">1</property><property name=\"page_increment"
  "\">10</property></object><object class=\"XfceTitledDialog\" id=\"main-d"
  "ialog\"><property name=\"can_focus\">False</property><property name=\"t"
  "itle\" translatable=\"yes\">Workspaces</property><property name=\"windo"
  "w_position\">center-on-parent</property><property name=\"icon_name\">xf"
  "ce4-workspaces</property><property name=\"type_hint\">dialog</property>"
  "<property name=\"subtitle\" translatable=\"yes\">Configure layout, name"
  "s and margins</property><child internal-child=\"vbox\"><object class=\""
  "GtkBox\" id=\"main-vbox\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"orientation\""
  ">vertical</property><property name=\"spacing\">2</property><child><obje"
  "ct class=\"GtkNotebook\" id=\"plug-child\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"border_width\">6</property><child><object class=\"GtkBox\" id=\"vbo"
  "x1\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"orientation\">vertical</property>"
  "<property name=\"border_width\">6</property><property name=\"spacing\">"
  "6</property><child><object class=\"GtkFrame\" id=\"frame4\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label_xalign\">0</property><property name=\"shado"
  "w_type\">none</property><child><object class=\"GtkAlignment\" id=\"alig"
  "nment4\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"top_padding\">6</property><pr"
  "operty name=\"bottom_padding\">6</property><property name=\"left_paddin"
  "g\">16</property><child><object class=\"GtkBox\" id=\"hbox3\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"orientation\">horizontal</property><property na"
  "me=\"spacing\">12</property><child><object class=\"GtkLabel\" id=\"labe"
  "l3\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">False</property><property name=\"xalign\">0</property><property na"
  "me=\"label\" translatable=\"yes\">_Number of workspaces:</property><pro"
  "perty name=\"use_underline\">True</property><property name=\"mnemonic_w"
  "idget\">workspace_count_spinbutton</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">0</property></packing></child><child><obj"
  "ect class=\"GtkSpinButton\" id=\"workspace_count_spinbutton\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"editable\">True</property><property name=\"invis"
  "ible_char\">\342\200\242</property><property name=\"primary_icon_activa"
  "table\">False</property><property name=\"secondary_icon_activatable\">F"
  "alse</property><property name=\"primary_icon_sensitive\">True</property"
  "><property name=\"secondary_icon_sensitive\">True</property><property n"
  "ame=\"adjustment\">adjustment1</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">1</property></packing></child></object></chi"
  "ld></object></child><child type=\"label\"><object class=\"GtkLabel\" id"
  "=\"label7\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">Layout</property><property name=\"use_markup\">True</property><attri"
  "butes><attribute name=\"weight\" value=\"bold\"/></attributes></object>"
  "</child></object><packing><property name=\"expand\">False</property><pr"
  "operty name=\"fill\">True</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkFrame\" id=\"frame5\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label_xalign\">0</property><property n"
  "ame=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"alignment5\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"top_padding\">6</pr"
  "operty><property name=\"left_padding\">18</property><child><object clas"
  "s=\"GtkScrolledWindow\" id=\"scrolledwindow1\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"hscrollbar_policy\">never</property><property name=\"vscrollbar"
  "_policy\">automatic</property><property name=\"shadow_type\">etched-in<"
  "/property><child><object class=\"GtkTreeView\" id=\"treeview_ws_names\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"rules_hint\">True</property></object><"
  "/child></object></child></object></child><child type=\"label\"><object "
  "class=\"GtkLabel\" id=\"label8\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"label"
  "\" translatable=\"yes\">Names</property><property name=\"use_markup\">T"
  "rue</property><attributes><attribute name=\"weight\" value=\"bold\"/></"
  "attributes></object></child></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object></child><child type=\""
  "tab\"><object class=\"GtkLabel\" id=\"label2\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label\" translatable=\"yes\">_General</property><property name"
  "=\"use_underline\">True</property></object><packing><property name=\"ta"
  "b_fill\">False</property></packing></child><child><object class=\"GtkBo"
  "x\" id=\"vbox2\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"orientation\">vertica"
  "l</property><property name=\"border_width\">6</property><property name="
  "\"spacing\">6</property><child><object class=\"GtkBox\" id=\"hbox1\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"orientation\">horizontal</property><prop"
  "erty name=\"spacing\">12</property><child><object class=\"GtkImage\" id"
  "=\"image1\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"stock\">gtk-info</property"
  "><property name=\"icon-size\">6</property></object><packing><property n"
  "ame=\"expand\">False</property><property name=\"fill\">True</property><"
  "property name=\"position\">0</property></packing></child><child><object"
  " class=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"xali"
  "gn\">0</property><property name=\"label\" translatable=\"yes\">Margins "
  "are areas on the edges of the screen where no window will be placed</pr"
  "operty><property name=\"wrap\">True</property></object><packing><proper"
  "ty name=\"expand\">True</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkAlignment\" id=\"alignment3\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"xscale\">0</property><property name=\"yscale\">0</"
  "property><child><object class=\"GtkTable\" id=\"table1\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"n_rows\">3</property><property name=\"n_columns\">3<"
  "/property><property name=\"column_spacing\">6</property><property name="
  "\"row_spacing\">6</property><child><placeholder/></child><child><placeh"
  "older/></child><child><object class=\"GtkSpinButton\" id=\"margin_left_"
  "spinbutton\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"invisible_char\">\342\200\242"
  "</property><property name=\"primary_icon_activatable\">False</property>"
  "<property name=\"secondary_icon_activatable\">False</property><property"
  " name=\"primary_icon_sensitive\">True</property><property name=\"second"
  "ary_icon_sensitive\">True</property><property name=\"adjustment\">adjus"
  "tment2</property></object><packing><property name=\"top_attach\">1</pro"
  "perty><property name=\"bottom_attach\">2</property><property name=\"x_o"
  "ptions\"/><property name=\"y_options\"/></packing></child><child><objec"
  "t class=\"GtkSpinButton\" id=\"margin_bottom_spinbutton\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"invisible_char\">\342\200\242</property><property na"
  "me=\"primary_icon_activatable\">False</property><property name=\"second"
  "ary_icon_activatable\">False</property><property name=\"primary_icon_se"
  "nsitive\">True</property><property name=\"secondary_icon_sensitive\">Tr"
  "ue</property><property name=\"adjustment\">adjustment3</property></obje"
  "ct><packing><property name=\"left_attach\">1</property><property name=\""
  "right_attach\">2</property><property name=\"top_attach\">2</property><p"
  "roperty name=\"bottom_attach\">3</property><property name=\"x_options\""
  "/><property name=\"y_options\"/></packing></child><child><object class="
  "\"GtkSpinButton\" id=\"margin_right_spinbutton\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"invisible_char\">\342\200\242</property><property name=\"prim"
  "ary_icon_activatable\">False</property><property name=\"secondary_icon_"
  "activatable\">False</property><property name=\"primary_icon_sensitive\""
  ">True</property><property name=\"secondary_icon_sensitive\">True</prope"
  "rty><property name=\"adjustment\">adjustment4</property></object><packi"
  "ng><property name=\"left_attach\">2</property><property name=\"right_at"
  "tach\">3</property><property name=\"top_attach\">1</property><property "
  "name=\"bottom_attach\">2</property><property name=\"x_options\"/><prope"
  "rty name=\"y_options\"/></packing></child><child><placeholder/></child>"
  "<child><object class=\"GtkImage\" id=\"monitor_icon\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xpad\">6</property><property name=\"ypad\">6</property>"
  "<property name=\"stock\">gtk-missing-image</property></object><packing>"
  "<property name=\"left_attach\">1</property><property name=\"right_attac"
  "h\">2</property><property name=\"top_attach\">1</property><property nam"
  "e=\"bottom_attach\">2</property></packing></child><child><object class="
  "\"GtkSpinButton\" id=\"margin_top_spinbutton\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"invisible_char\">\342\200\242</property><property name=\"primar"
  "y_icon_activatable\">False</property><property name=\"secondary_icon_ac"
  "tivatable\">False</property><property name=\"primary_icon_sensitive\">T"
  "rue</property><property name=\"secondary_icon_sensitive\">True</propert"
  "y><property name=\"adjustment\">adjustment5</property></object><packing"
  "><property name=\"left_attach\">1</property><property name=\"right_atta"
  "ch\">2</property><property name=\"x_options\"/><property name=\"y_optio"
  "ns\"/></packing></child><child><placeholder/></child><child><placeholde"
  "r/></child><child><placeholder/></child><child><placeholder/></child></"
  "object></child></object><packing><property name=\"expand\">True</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">1"
  "</property></packing></child></object><packing><property name=\"positio"
  "n\">1</property></packing></child><child type=\"tab\"><object class=\"G"
  "tkLabel\" id=\"label6\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"label\" transl"
  "atable=\"yes\">_Margins</property><property name=\"use_underline\">True"
  "</property></object><packing><property name=\"position\">1</property><p"
  "roperty name=\"tab_fill\">False</property></packing></child></object><p"
  "acking><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child internal-child=\"action_area\"><object class=\"GtkButtonBox\""
  " id=\"dialog-action_area1\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"orientatio"
  "n\">horizontal</property><property name=\"layout_style\">end</property>"
  "<child><object class=\"GtkButton\" id=\"button2\"><property name=\"labe"
  "l\">gtk-help</property><property name=\"use_action_appearance\">False</"
  "property><property name=\"visible\">True</property><property name=\"can"
  "_focus\">True</property><property name=\"receives_default\">True</prope"
  "rty><property name=\"use_stock\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">0</property><property name=\"secondar"
  "y\">True</property></packing></child><child><object class=\"GtkButton\""
  " id=\"button1\"><property name=\"label\">gtk-close</property><property "
  "name=\"use_action_appearance\">False</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">True</property><property name=\"use_stock\">"
  "True</property></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property><property name=\"pack_type\""
  ">end</property><property name=\"position\">1</property></packing></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">True</property><property name=\"pack_type\">end</propert"
  "y><property name=\"position\">0</property></packing></child></object></"
  "child><action-widgets><action-widget response=\"-11\">button2</action-w"
  "idget><action-widget response=\"0\">button1</action-widget></action-wid"
  "gets></object></interface>"
};

static const unsigned workspace_dialog_ui_length = 14013u;

