/* automatically generated from xfwm4-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfwm4_dialog_ui)
#endif
#ifdef __GNUC__
static const char xfwm4_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfwm4_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><object class=\"GtkAdjustment\" id=\"adjustment1"
  "\"><property name=\"lower\">5</property><property name=\"upper\">2000</"
  "property><property name=\"value\">5</property><property name=\"step_inc"
  "rement\">1</property><property name=\"page_increment\">10</property></o"
  "bject><object class=\"GtkAdjustment\" id=\"adjustment2\"><property name"
  "=\"lower\">5</property><property name=\"upper\">2000</property><propert"
  "y name=\"value\">5</property><property name=\"step_increment\">1</prope"
  "rty><property name=\"page_increment\">10</property></object><object cla"
  "ss=\"GtkAdjustment\" id=\"adjustment3\"><property name=\"lower\">5</pro"
  "perty><property name=\"upper\">100</property><property name=\"value\">2"
  "0</property><property name=\"step_increment\">1</property><property nam"
  "e=\"page_increment\">10</property></object><object class=\"GtkAdjustmen"
  "t\" id=\"adjustment4\"><property name=\"lower\">5</property><property n"
  "ame=\"upper\">100</property><property name=\"value\">20</property><prop"
  "erty name=\"step_increment\">1</property><property name=\"page_incremen"
  "t\">10</property></object><object class=\"XfceTitledDialog\" id=\"main-"
  "dialog\"><property name=\"can_focus\">False</property><property name=\""
  "title\" translatable=\"yes\">Window Manager</property><property name=\""
  "window_position\">center-on-parent</property><property name=\"icon_name"
  "\">xfwm4</property><property name=\"type_hint\">dialog</property><prope"
  "rty name=\"subtitle\" translatable=\"yes\">Configure window behavior an"
  "d shortcuts</property><child internal-child=\"vbox\"><object class=\"Gt"
  "kBox\" id=\"main-vbox\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"orientation\">"
  "vertical</property><child internal-child=\"action_area\"><object class="
  "\"GtkButtonBox\" id=\"dialog-action_area1\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"orientation\">horizontal</property><property name=\"layout_style\""
  ">end</property><child><object class=\"GtkButton\" id=\"help_button\"><p"
  "roperty name=\"label\">gtk-help</property><property name=\"use_action_a"
  "ppearance\">False</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"receives_de"
  "fault\">True</property><property name=\"use_stock\">True</property></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">False</property><property name=\"position\">0</property><prope"
  "rty name=\"secondary\">True</property></packing></child><child><object "
  "class=\"GtkButton\" id=\"close_button\"><property name=\"label\">gtk-cl"
  "ose</property><property name=\"use_action_appearance\">False</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">True</property><prop"
  "erty name=\"use_stock\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">1</property></packing></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"pack_type\">end</property><property name=\""
  "position\">0</property></packing></child><child><object class=\"GtkNote"
  "book\" id=\"plug-child\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"border_width\""
  ">6</property><child><object class=\"GtkBox\" id=\"hbox7\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"orientation\">horizontal</property><property name=\""
  "border_width\">12</property><property name=\"spacing\">12</property><ch"
  "ild><object class=\"GtkFrame\" id=\"frame13\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label_xalign\">0</property><property name=\"shadow_type\">none</"
  "property><child><object class=\"GtkAlignment\" id=\"alignment11\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"top_padding\">6</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkScrolledWindow\" "
  "id=\"scrolledwindow3\"><property name=\"width_request\">200</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"hscrollbar_policy\">automatic</property>"
  "<property name=\"vscrollbar_policy\">automatic</property><property name"
  "=\"shadow_type\">in</property><child><object class=\"GtkTreeView\" id=\""
  "theme_name_treeview\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">True</property><property name=\"headers_visible\""
  ">False</property></object></child></object></child></object></child><ch"
  "ild type=\"label\"><object class=\"GtkLabel\" id=\"label32\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"label\" translatable=\"yes\">&lt;b&gt;The_me&lt;"
  "/b&gt;</property><property name=\"use_markup\">True</property><property"
  " name=\"use_underline\">True</property></object></child></object><packi"
  "ng><property name=\"expand\">True</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkBox\" id=\"vbox12\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"orientation\">vertical</property><property name=\"spacing\">6</p"
  "roperty><child><object class=\"GtkFrame\" id=\"frame10\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"label_xalign\">0</property><property name=\"shadow_t"
  "ype\">none</property><child><object class=\"GtkAlignment\" id=\"alignme"
  "nt14\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"border_width\">6</property><pro"
  "perty name=\"bottom_padding\">6</property><property name=\"left_padding"
  "\">12</property><child><object class=\"GtkFontButton\" id=\"title_font_"
  "button\"><property name=\"use_action_appearance\">False</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">True</property></object><"
  "/child></object></child><child type=\"label\"><object class=\"GtkLabel\""
  " id=\"label23\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">&lt;b&gt;Title fon_t&lt;/b&gt;</property><property name=\"use_mar"
  "kup\">True</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"mnemonic_widget\">title_font_button</property></object><"
  "/child></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">0</prop"
  "erty></packing></child><child><object class=\"GtkFrame\" id=\"frame11\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label_xalign\">0</property><property "
  "name=\"shadow_type\">none</property><child><object class=\"GtkAlignment"
  "\" id=\"title_align_box\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"border_width"
  "\">6</property><property name=\"bottom_padding\">6</property><property "
  "name=\"left_padding\">12</property><child><object class=\"GtkComboBox\""
  " id=\"title_align_combo\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property></object></child></object></c"
  "hild><child type=\"label\"><object class=\"GtkLabel\" id=\"label24\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Ti"
  "tle _alignment&lt;/b&gt;</property><property name=\"use_markup\">True</"
  "property><property name=\"use_underline\">True</property><property name"
  "=\"mnemonic_widget\">title_align_combo</property></object></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">1</property></packin"
  "g></child><child><object class=\"GtkFrame\" id=\"frame12\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label_xalign\">0</property><property name=\"shadow"
  "_type\">none</property><child><object class=\"GtkAlignment\" id=\"butto"
  "n_layout_box\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"bottom_padding\">6</pro"
  "perty><property name=\"left_padding\">12</property><child><object class"
  "=\"GtkBox\" id=\"vbox13\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"orientation\""
  ">vertical</property><property name=\"border_width\">6</property><proper"
  "ty name=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\""
  "label26\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"xalign\">0</property><proper"
  "ty name=\"label\" translatable=\"yes\">Click and drag the buttons to ch"
  "ange the layout</property></object><packing><property name=\"expand\">T"
  "rue</property><property name=\"fill\">True</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkFrame"
  "\" id=\"active-frame\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label_xalign\">"
  "0</property><child><object class=\"GtkAlignment\" id=\"alignment17\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"border_width\">6</property><child><objec"
  "t class=\"GtkBox\" id=\"active-box\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"o"
  "rientation\">horizontal</property><property name=\"spacing\">6</propert"
  "y><child><object class=\"GtkButton\" id=\"button-layout-|\"><property n"
  "ame=\"label\" translatable=\"yes\">Title</property><property name=\"use"
  "_action_appearance\">False</property><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">True</property><property name=\"re"
  "ceives_default\">True</property><property name=\"tooltip_text\" transla"
  "table=\"yes\">The window title cannot be removed</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild></object></child></object></child><child type=\"label\"><object cla"
  "ss=\"GtkLabel\" id=\"label27\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">Active</property><property name=\"use_markup\">Tr"
  "ue</property></object></child></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">1</property></packing></child><child><object class=\"GtkF"
  "rame\" id=\"hidden-frame\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label_xalig"
  "n\">0</property><child><object class=\"GtkAlignment\" id=\"alignment18\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><child><ob"
  "ject class=\"GtkBox\" id=\"hidden-box\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"orientation\">horizontal</property><property name=\"spacing\">6</prop"
  "erty><child><object class=\"GtkButton\" id=\"button-layout-O\"><propert"
  "y name=\"use_action_appearance\">False</property><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"receives_default\">True</property><property name=\"tooltip_te"
  "xt\" translatable=\"yes\">Menu</property><child><object class=\"GtkImag"
  "e\" id=\"image1\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"icon_name\">xfce-wm-"
  "menu</property></object></child></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkButton\" id=\"button-layout-T\"><property name=\"use_action_appearan"
  "ce\">False</property><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">True</property><property name=\"tooltip_text\" translatable=\"yes\">St"
  "ick</property><child><object class=\"GtkImage\" id=\"image2\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"icon_name\">xfce-wm-stick</property></object></"
  "child></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">1</prope"
  "rty></packing></child><child><object class=\"GtkButton\" id=\"button-la"
  "yout-S\"><property name=\"use_action_appearance\">False</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">True</property><property "
  "name=\"tooltip_text\" translatable=\"yes\">Shade</property><child><obje"
  "ct class=\"GtkImage\" id=\"image3\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"ic"
  "on_name\">xfce-wm-shade</property></object></child></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">2</property></packing></child><chi"
  "ld><object class=\"GtkButton\" id=\"button-layout-H\"><property name=\""
  "use_action_appearance\">False</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"tooltip_text\" trans"
  "latable=\"yes\">Minimize</property><child><object class=\"GtkImage\" id"
  "=\"image4\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"icon_name\">xfce-wm-minimi"
  "ze</property></object></child></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"position\">3</property></packing></child><child><object class=\"Gt"
  "kButton\" id=\"button-layout-M\"><property name=\"use_action_appearance"
  "\">False</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">T"
  "rue</property><property name=\"tooltip_text\" translatable=\"yes\">Maxi"
  "mize</property><child><object class=\"GtkImage\" id=\"image5\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"icon_name\">xfce-wm-maximize</property></objec"
  "t></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">False</property><property name=\"position\">4</p"
  "roperty></packing></child><child><object class=\"GtkButton\" id=\"butto"
  "n-layout-C\"><property name=\"use_action_appearance\">False</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"receives_default\">True</property><prope"
  "rty name=\"tooltip_text\" translatable=\"yes\">Close</property><child><"
  "object class=\"GtkImage\" id=\"image6\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"icon_name\">xfce-wm-close</property></object></child></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"position\">5</property></packing></child>"
  "</object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label28\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">Hidden</property><property name=\"use_markup\">True</p"
  "roperty></object></child></object><packing><property name=\"expand\">Tr"
  "ue</property><property name=\"fill\">True</property><property name=\"po"
  "sition\">2</property></packing></child></object></child></object></chil"
  "d><child type=\"label\"><object class=\"GtkLabel\" id=\"label25\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Butto"
  "n layout&lt;/b&gt;</property><property name=\"use_markup\">True</proper"
  "ty></object></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">2</property></packing></child></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">1</property></packing></child></object></child><chi"
  "ld type=\"tab\"><object class=\"GtkLabel\" id=\"label1\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"label\" translatable=\"yes\">_Style</property><prope"
  "rty name=\"use_underline\">True</property></object><packing><property n"
  "ame=\"tab_fill\">False</property></packing></child><child><object class"
  "=\"GtkBox\" id=\"vbox10\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"orientation\""
  ">vertical</property><property name=\"border_width\">12</property><prope"
  "rty name=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\""
  "label22\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"xalign\">0</property><proper"
  "ty name=\"label\" translatable=\"yes\">Define shortcuts to perform _win"
  "dow manager actions:</property><property name=\"use_markup\">True</prop"
  "erty><property name=\"use_underline\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">0</property></packing></child><c"
  "hild><object class=\"GtkBox\" id=\"vbox11\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"orientation\">vertical</property><property name=\"spacing\">6</pr"
  "operty><child><object class=\"GtkScrolledWindow\" id=\"scrolledwindow2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"hscrollbar_policy\">never</property><p"
  "roperty name=\"vscrollbar_policy\">automatic</property><property name=\""
  "shadow_type\">in</property><child><object class=\"GtkTreeView\" id=\"sh"
  "ortcuts_treeview\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property></object></child></object><packing><p"
  "roperty name=\"expand\">True</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">0</property></packing></child><child"
  "><placeholder/></child></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">1</property></packing></child><child><object class=\"GtkAlignmen"
  "t\" id=\"alignment15\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"yalign\">0</pro"
  "perty><property name=\"xscale\">0</property><child><object class=\"GtkB"
  "ox\" id=\"hbox5\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"orientation\">horizo"
  "ntal</property><property name=\"spacing\">6</property><child><object cl"
  "ass=\"GtkButton\" id=\"shortcuts_edit_button\"><property name=\"label\""
  ">gtk-edit</property><property name=\"use_action_appearance\">False</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">True</property"
  "><property name=\"use_stock\">True</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkButton\" id=\"shortcuts_clear_button\"><property name=\""
  "label\">gtk-clear</property><property name=\"use_action_appearance\">Fa"
  "lse</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">True</"
  "property><property name=\"use_stock\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">1</property></packing></child><c"
  "hild><object class=\"GtkButton\" id=\"shortcuts_reset_button\"><propert"
  "y name=\"label\" translatable=\"yes\">_Reset to Defaults</property><pro"
  "perty name=\"use_action_appearance\">False</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">True</property><pr"
  "operty name=\"receives_default\">True</property><property name=\"use_un"
  "derline\">True</property></object><packing><property name=\"expand\">Fa"
  "lse</property><property name=\"fill\">False</property><property name=\""
  "padding\">15</property><property name=\"pack_type\">end</property><prop"
  "erty name=\"position\">2</property></packing></child></object></child><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">False</property><property name=\"position\">2</property></p"
  "acking></child></object><packing><property name=\"position\">1</propert"
  "y></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label2\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "_Keyboard</property><property name=\"use_underline\">True</property></o"
  "bject><packing><property name=\"position\">1</property><property name=\""
  "tab_fill\">False</property></packing></child><child><object class=\"Gtk"
  "Box\" id=\"vbox7\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"orientation\">verti"
  "cal</property><property name=\"border_width\">12</property><property na"
  "me=\"spacing\">6</property><child><object class=\"GtkFrame\" id=\"frame"
  "5\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"label_xalign\">0</property><proper"
  "ty name=\"shadow_type\">none</property><child><object class=\"GtkAlignm"
  "ent\" id=\"alignment7\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"border_width\""
  ">6</property><property name=\"bottom_padding\">6</property><property na"
  "me=\"left_padding\">12</property><child><object class=\"GtkBox\" id=\"v"
  "box14\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"orientation\">vertical</proper"
  "ty><property name=\"spacing\">6</property><child><object class=\"GtkBox"
  "\" id=\"hbox3\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"orientation\">horizont"
  "al</property><property name=\"spacing\">12</property><property name=\"h"
  "omogeneous\">True</property><child><object class=\"GtkRadioButton\" id="
  "\"click_to_focus_radio\"><property name=\"label\" translatable=\"yes\">"
  "Click to foc_us</property><property name=\"use_action_appearance\">Fals"
  "e</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">False</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"draw_indicator\">True</property></object><packing><property name=\"ex"
  "pand\">True</property><property name=\"fill\">True</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkRadioButton\" id=\"focus_follows_mouse_radio\"><property name=\"labe"
  "l\" translatable=\"yes\">Focus follows _mouse</property><property name="
  "\"use_action_appearance\">False</property><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">True</property><property name"
  "=\"receives_default\">False</property><property name=\"use_underline\">"
  "True</property><property name=\"draw_indicator\">True</property><proper"
  "ty name=\"group\">click_to_focus_radio</property></object><packing><pro"
  "perty name=\"expand\">True</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">1</property></packing></child></object"
  "><packing><property name=\"expand\">True</property><property name=\"fil"
  "l\">True</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkLabel\" id=\"label29\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">_Delay before window receives focus:</property><property na"
  "me=\"use_markup\">True</property><property name=\"use_underline\">True<"
  "/property><property name=\"mnemonic_widget\">focus_delay_scale</propert"
  "y></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">1</property></"
  "packing></child><child><object class=\"GtkAlignment\" id=\"alignment19\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"left_padding\">12</property><child><o"
  "bject class=\"GtkBox\" id=\"focus_delay_hbox\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"orientation\">horizontal</property><property name=\"spacing\">"
  "12</property><child><object class=\"GtkLabel\" id=\"label30\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label\" translatable=\"yes\" comments=\"Focus d"
  "elay\">&lt;i&gt;Short&lt;/i&gt;</property><property name=\"use_markup\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkScale\" id=\"f"
  "ocus_delay_scale\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"orientation\">horizo"
  "ntal</property><property name=\"adjustment\">adjustment1</property><pro"
  "perty name=\"draw_value\">False</property></object><packing><property n"
  "ame=\"expand\">True</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">1</property></packing></child><child><object "
  "class=\"GtkLabel\" id=\"label31\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\" comments=\"Focus delay\">&lt;i&gt;Long&lt;/i&g"
  "t;</property><property name=\"use_markup\">True</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">2</property></packing></chi"
  "ld></object></child></object><packing><property name=\"expand\">True</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">2</property></packing></child></object></child></object></child><ch"
  "ild type=\"label\"><object class=\"GtkLabel\" id=\"label15\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Focus mode"
  "l&lt;/b&gt;</property><property name=\"use_markup\">True</property></ob"
  "ject></child></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">0"
  "</property></packing></child><child><object class=\"GtkFrame\" id=\"fra"
  "me6\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"label_xalign\">0</property><prop"
  "erty name=\"shadow_type\">none</property><child><object class=\"GtkAlig"
  "nment\" id=\"alignment8\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"border_width"
  "\">6</property><property name=\"bottom_padding\">6</property><property "
  "name=\"left_padding\">12</property><child><object class=\"GtkCheckButto"
  "n\" id=\"focus_new_check\"><property name=\"label\" translatable=\"yes\""
  ">Automatically give focus to _newly created windows</property><property"
  " name=\"use_action_appearance\">False</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">False</property><property name=\"use_underl"
  "ine\">True</property><property name=\"draw_indicator\">True</property><"
  "/object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label16\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">&lt;b&gt;New window focus&lt;/b&gt;</property><propert"
  "y name=\"use_markup\">True</property></object></child></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"position\">1</property></packing></child><"
  "child><object class=\"GtkFrame\" id=\"frame7\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label_xalign\">0</property><property name=\"shadow_type\">none"
  "</property><child><object class=\"GtkAlignment\" id=\"alignment9\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"border_width\">6</property><property name="
  "\"bottom_padding\">6</property><property name=\"left_padding\">12</prop"
  "erty><child><object class=\"GtkBox\" id=\"vbox8\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"orientation\">vertical</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkCheckButton\" id=\"raise_on_focu"
  "s_check\"><property name=\"label\" translatable=\"yes\">Automatically _"
  "raise windows when they receive focus</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"draw_indicator\">True</property></object><packi"
  "ng><property name=\"expand\">True</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkBox\" id=\"vbox9\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"orientation\">vertical</property><property name=\"spacing\">6</pr"
  "operty><child><object class=\"GtkLabel\" id=\"label19\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"xalign\">0</property><property name=\"label\" transla"
  "table=\"yes\">Delay _before raising focused window:</property><property"
  " name=\"use_underline\">True</property><property name=\"mnemonic_widget"
  "\">focus_raise_delay_scale</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkAlignment\" id=\"alignment1\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "eft_padding\">12</property><child><object class=\"GtkBox\" id=\"hbox4\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"orientation\">horizontal</property><p"
  "roperty name=\"spacing\">12</property><child><object class=\"GtkLabel\""
  " id=\"label20\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\" comments=\"Raise focus delay\">&lt;i&gt;Short&lt;/i&gt;</property"
  "><property name=\"use_markup\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">False</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkScale\" id=\"focus_raise_delay_scale\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"orientation\">horizontal</property><property name=\"ad"
  "justment\">adjustment2</property><property name=\"draw_value\">False</p"
  "roperty></object><packing><property name=\"expand\">True</property><pro"
  "perty name=\"fill\">True</property><property name=\"position\">1</prope"
  "rty></packing></child><child><object class=\"GtkLabel\" id=\"label21\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label\" translatable=\"yes\" comments="
  "\"Raise focus delay\">&lt;i&gt;Long&lt;/i&gt;</property><property name="
  "\"use_markup\">True</property></object><packing><property name=\"expand"
  "\">False</property><property name=\"fill\">False</property><property na"
  "me=\"position\">2</property></packing></child></object></child></object"
  "><packing><property name=\"expand\">True</property><property name=\"fil"
  "l\">True</property><property name=\"position\">1</property></packing></"
  "child></object><packing><property name=\"expand\">True</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">1</propert"
  "y></packing></child></object></child></object></child><child type=\"lab"
  "el\"><object class=\"GtkLabel\" id=\"label17\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"label\" translatable=\"yes\">&lt;b&gt;Raise on focus&lt;/b&gt;"
  "</property><property name=\"use_markup\">True</property></object></chil"
  "d></object><packing><property name=\"expand\">False</property><property"
  " name=\"fill\">False</property><property name=\"position\">2</property>"
  "</packing></child><child><object class=\"GtkFrame\" id=\"frame8\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"label_xalign\">0</property><property name=\""
  "shadow_type\">none</property><child><object class=\"GtkAlignment\" id=\""
  "alignment10\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"border_width\">6</proper"
  "ty><property name=\"bottom_padding\">6</property><property name=\"left_"
  "padding\">12</property><child><object class=\"GtkCheckButton\" id=\"rai"
  "se_on_click_check\"><property name=\"label\" translatable=\"yes\">Raise"
  " window when clicking _inside application window</property><property na"
  "me=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject></child></object></child><child type=\"label\"><object class=\"Gtk"
  "Label\" id=\"label18\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label\" transla"
  "table=\"yes\">&lt;b&gt;Raise on click&lt;/b&gt;</property><property nam"
  "e=\"use_markup\">True</property></object></child></object><packing><pro"
  "perty name=\"expand\">False</property><property name=\"fill\">False</pr"
  "operty><property name=\"position\">3</property></packing></child></obje"
  "ct><packing><property name=\"position\">2</property></packing></child><"
  "child type=\"tab\"><object class=\"GtkLabel\" id=\"label3\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"label\" translatable=\"yes\">_Focus</property><pr"
  "operty name=\"use_underline\">True</property></object><packing><propert"
  "y name=\"position\">2</property><property name=\"tab_fill\">False</prop"
  "erty></packing></child><child><object class=\"GtkBox\" id=\"vbox1\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"orientation\">vertical</property><propert"
  "y name=\"border_width\">12</property><property name=\"spacing\">6</prop"
  "erty><child><object class=\"GtkFrame\" id=\"frame1\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"label_xalign\">0</property><property name=\"shadow_type\""
  ">none</property><child><object class=\"GtkAlignment\" id=\"alignment2\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"bottom_padding\">6</property><property name=\"left_padding\">12<"
  "/property><child><object class=\"GtkBox\" id=\"vbox2\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"orientation\">vertical</property><property name=\"spaci"
  "ng\">6</property><child><object class=\"GtkBox\" id=\"hbox8\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"orientation\">horizontal</property><child><obje"
  "ct class=\"GtkCheckButton\" id=\"snap_to_border_check\"><property name="
  "\"label\" translatable=\"yes\">To screen _borders</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkCheckButton\" id=\"snap_to_window_ch"
  "eck\"><property name=\"label\" translatable=\"yes\">To other _windows</"
  "property><property name=\"use_action_appearance\">False</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "1</property></packing></child></object><packing><property name=\"expand"
  "\">True</property><property name=\"fill\">True</property><property name"
  "=\"position\">0</property></packing></child><child><object class=\"GtkB"
  "ox\" id=\"vbox5\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"orientation\">vertic"
  "al</property><property name=\"spacing\">6</property><child><object clas"
  "s=\"GtkLabel\" id=\"label9\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"xalign\">"
  "0</property><property name=\"label\" translatable=\"yes\">Dis_tance:</p"
  "roperty><property name=\"use_underline\">True</property><property name="
  "\"mnemonic_widget\">snap_width_scale</property></object><packing><prope"
  "rty name=\"expand\">True</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkAlignment\" id=\"alignment6\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"left_padding\">12</property><child><object class=\"GtkBox\" id=\""
  "hbox1\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"orientation\">horizontal</prop"
  "erty><property name=\"spacing\">12</property><child><object class=\"Gtk"
  "Label\" id=\"label11\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label\" transla"
  "table=\"yes\" comments=\"Snapping distance\">&lt;i&gt;Small&lt;/i&gt;</"
  "property><property name=\"use_markup\">True</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkScale\" id=\"snap_width_scale\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">True</property"
  "><property name=\"orientation\">horizontal</property><property name=\"a"
  "djustment\">adjustment3</property><property name=\"restrict_to_fill_lev"
  "el\">False</property><property name=\"draw_value\">False</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child><child><object class=\"GtkLabel\" id=\"label12\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label\" translatable=\"yes\" comments=\"Snapping di"
  "stance\">&lt;i&gt;Wide&lt;/i&gt;</property><property name=\"use_markup\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">2</property></packing></child></object></child></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child></object>"
  "<packing><property name=\"expand\">True</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild></object></child></object></child><child type=\"label\"><object cl"
  "ass=\"GtkLabel\" id=\"label5\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">&lt;b&gt;Windows snapping&lt;/b&gt;</property><pr"
  "operty name=\"use_markup\">True</property></object></child></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkFrame\" id=\"frame2\"><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"label_xalign\">0</property><property name=\"shadow_type\">"
  "none</property><child><object class=\"GtkAlignment\" id=\"alignment3\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"border_width\">6</property><property n"
  "ame=\"bottom_padding\">6</property><property name=\"left_padding\">12</"
  "property><child><object class=\"GtkBox\" id=\"vbox4\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"orientation\">vertical</property><property name=\"spaci"
  "ng\">6</property><child><object class=\"GtkBox\" id=\"hbox9\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"orientation\">horizontal</property><child><obje"
  "ct class=\"GtkCheckButton\" id=\"wrap_workspaces_check\"><property name"
  "=\"label\" translatable=\"yes\">With the mouse _pointer</property><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">False</property><property name=\"use_un"
  "derline\">True</property><property name=\"draw_indicator\">True</proper"
  "ty></object><packing><property name=\"expand\">True</property><property"
  " name=\"fill\">True</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkCheckButton\" id=\"wrap_wind"
  "ows_check\"><property name=\"label\" translatable=\"yes\">With a _dragg"
  "ed window</property><property name=\"use_action_appearance\">False</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">False</propert"
  "y><property name=\"use_underline\">True</property><property name=\"draw"
  "_indicator\">True</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object><packing><property na"
  "me=\"expand\">True</property><property name=\"fill\">True</property><pr"
  "operty name=\"position\">0</property></packing></child><child><object c"
  "lass=\"GtkBox\" id=\"vbox6\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"orientati"
  "on\">vertical</property><property name=\"spacing\">6</property><child><"
  "object class=\"GtkLabel\" id=\"label10\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"xalign\">0</property><property name=\"label\" translatable=\"yes\">_"
  "Edge resistance:</property><property name=\"use_underline\">True</prope"
  "rty><property name=\"selectable\">True</property><property name=\"mnemo"
  "nic_widget\">wrap_resistance_scale</property></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">0</property></packing></child><child><ob"
  "ject class=\"GtkAlignment\" id=\"alignment4\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"left_padding\">12</property><child><object class=\"GtkBox\" id=\""
  "hbox2\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"orientation\">horizontal</prop"
  "erty><property name=\"spacing\">12</property><child><object class=\"Gtk"
  "Label\" id=\"label13\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"label\" transla"
  "table=\"yes\" comments=\"Edge resistance\">&lt;i&gt;Small&lt;/i&gt;</pr"
  "operty><property name=\"use_markup\">True</property></object><packing><"
  "property name=\"expand\">False</property><property name=\"fill\">False<"
  "/property><property name=\"position\">0</property></packing></child><ch"
  "ild><object class=\"GtkScale\" id=\"wrap_resistance_scale\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">True</prope"
  "rty><property name=\"orientation\">horizontal</property><property name="
  "\"adjustment\">adjustment4</property><property name=\"restrict_to_fill_"
  "level\">False</property><property name=\"draw_value\">False</property><"
  "/object><packing><property name=\"expand\">True</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">1</property></pac"
  "king></child><child><object class=\"GtkLabel\" id=\"label14\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label\" translatable=\"yes\" comments=\"Edge re"
  "sistance\">&lt;i&gt;Wide&lt;/i&gt;</property><property name=\"use_marku"
  "p\">True</property></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">False</property><property name=\"positi"
  "on\">2</property></packing></child></object></child></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">1</property></packing></child></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label6\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">&lt;b&gt;Wrap workspaces when reaching the sc"
  "reen edge&lt;/b&gt;</property><property name=\"use_markup\">True</prope"
  "rty></object></child></object><packing><property name=\"expand\">False<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkFrame\" i"
  "d=\"frame3\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label_xalign\">0</property"
  "><property name=\"shadow_type\">none</property><child><object class=\"G"
  "tkAlignment\" id=\"alignment5\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"border"
  "_width\">6</property><property name=\"bottom_padding\">6</property><pro"
  "perty name=\"left_padding\">12</property><child><object class=\"GtkBox\""
  " id=\"hbox6\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"orientation\">horizontal"
  "</property><child><object class=\"GtkCheckButton\" id=\"box_move_check\""
  "><property name=\"label\" translatable=\"yes\">When _moving</property><"
  "property name=\"use_action_appearance\">False</property><property name="
  "\"visible\">True</property><property name=\"can_focus\">True</property>"
  "<property name=\"receives_default\">False</property><property name=\"us"
  "e_underline\">True</property><property name=\"draw_indicator\">True</pr"
  "operty></object><packing><property name=\"expand\">True</property><prop"
  "erty name=\"fill\">True</property><property name=\"position\">0</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"box_r"
  "esize_check\"><property name=\"label\" translatable=\"yes\">When _resiz"
  "ing</property><property name=\"use_action_appearance\">False</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">False</property><pro"
  "perty name=\"use_underline\">True</property><property name=\"draw_indic"
  "ator\">True</property></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child></object></child></object></child><"
  "child type=\"label\"><object class=\"GtkLabel\" id=\"label7\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Hide cont"
  "ent of windows&lt;/b&gt;</property><property name=\"use_markup\">True</"
  "property></object></child></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property name=\""
  "position\">2</property></packing></child><child><object class=\"GtkFram"
  "e\" id=\"frame4\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"label_xalign\">0</pr"
  "operty><property name=\"shadow_type\">none</property><child><object cla"
  "ss=\"GtkAlignment\" id=\"alignment13\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "top_padding\">6</property><property name=\"bottom_padding\">6</property"
  "><property name=\"left_padding\">18</property><child><object class=\"Gt"
  "kComboBox\" id=\"double_click_action_combo\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"tooltip_text\" translatable=\"yes\">The action to perform when t"
  "he title-bar is double-clicked</property></object></child></object></ch"
  "ild><child type=\"label\"><object class=\"GtkLabel\" id=\"label8\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Doub"
  "le click _action&lt;/b&gt;</property><property name=\"use_markup\">True"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"mnemonic_widget\">double_click_action_combo</property></object></c"
  "hild></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">True</property><property name=\"position\">3</propert"
  "y></packing></child></object><packing><property name=\"position\">3</pr"
  "operty></packing></child><child type=\"tab\"><object class=\"GtkLabel\""
  " id=\"label4\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">Ad_vanced</property><property name=\"use_underline\">True</proper"
  "ty></object><packing><property name=\"position\">3</property><property "
  "name=\"tab_fill\">False</property></packing></child></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">1</property></packing></child></obj"
  "ect></child><action-widgets><action-widget response=\"-11\">help_button"
  "</action-widget><action-widget response=\"0\">close_button</action-widg"
  "et></action-widgets></object><object class=\"GtkSizeGroup\" id=\"sizegr"
  "oup1\"><property name=\"mode\">vertical</property><widgets><widget name"
  "=\"alignment17\"/><widget name=\"alignment18\"/></widgets></object></in"
  "terface>"
};

static const unsigned xfwm4_dialog_ui_length = 49371u;

